<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
    'WPUserManager\\Stripe\\' => array($baseDir . '/includes/integrations/stripe'),
    'WPUM\\WPUserManagerBlocks\\' => array($vendorDir . '/wp-user-manager/wpum-blocks/includes/classes'),
    'WPUM\\Symfony\\Polyfill\\Php80\\' => array($vendorDir . '/symfony/polyfill-php80'),
    'WPUM\\Symfony\\Polyfill\\Mbstring\\' => array($vendorDir . '/symfony/polyfill-mbstring'),
    'WPUM\\Symfony\\Contracts\\Translation\\' => array($vendorDir . '/symfony/translation-contracts'),
    'WPUM\\Symfony\\Component\\Translation\\' => array($vendorDir . '/symfony/translation'),
    'WPUM\\Svg\\' => array($vendorDir . '/phenx/php-svg-lib/src/Svg'),
    'WPUM\\Stripe\\' => array($vendorDir . '/stripe/stripe-php/lib'),
    'WPUM\\Sabberworm\\CSS\\' => array($vendorDir . '/sabberworm/php-css-parser/src'),
    'WPUM\\Psr\\Http\\Message\\' => array($vendorDir . '/psr/http-message/src'),
    'WPUM\\Masterminds\\' => array($vendorDir . '/masterminds/html5/src'),
    'WPUM\\FontLib\\' => array($vendorDir . '/phenx/php-font-lib/src/FontLib'),
    'WPUM\\FastRoute\\' => array($vendorDir . '/nikic/fast-route/src'),
    'WPUM\\Dompdf\\' => array($vendorDir . '/dompdf/dompdf/src'),
    'WPUM\\Composer\\Installers\\' => array($vendorDir . '/composer/installers/src/Composer/Installers'),
    'WPUM\\Carbon_Fields\\' => array($vendorDir . '/htmlburger/carbon-fields/core'),
    'WPUM\\Carbon\\' => array($vendorDir . '/nesbot/carbon/src/Carbon'),
    'WPUM\\Brain\\' => array($vendorDir . '/brain/cortex/src'),
);
